In [1]:
import pickle
import numpy as np

In [2]:
# loading pre-trained objects
ohe_sex = pickle.load(open('ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('clf.pkl', 'rb'))


In [3]:
# Assume User Input
# PClass/Sex/Age/SibSp/Parch/Fare/Embarked
test_input = np.array([3, 'male', 35.0, 0, 0, 8.0500, 'S'], dtype=object).reshape(1, 7)

In [4]:
test_input

array([[3, 'male', 35.0, 0, 0, 8.05, 'S']], dtype=object)

In [5]:
# OneHotEncoding input sex
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1, 1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [6]:
test_input_sex

array([[0., 1.]])

In [7]:
# OneHotEncoding input embarked
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))

In [8]:
test_input_embarked

array([[0., 0., 1.]])

In [9]:
# combining all the columns
test_input_transformed = np.concatenate((test_input[:, [0, 2, 3, 4, 5]], test_input_sex, test_input_embarked), axis=1)

In [10]:
test_input_transformed.shape

(1, 10)

In [11]:
# making prediction
clf.predict(test_input_transformed)

array([0])