In [1]:
import numpy as np
import pandas as pd

In [12]:
from xgboost import XGBClassifier
from sklearn.feature_selection import RFECV
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import load_breast_cancer

In [13]:
data = load_breast_cancer()

In [14]:
X, y = data.data, data.target

In [15]:
model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')


In [16]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [17]:
rfecv = RFECV(
    estimator=model,
    step=1,
    cv=cv,
    scoring='accuracy',
    min_features_to_select=1,
)

In [18]:
rfecv.fit(X, y)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [13:27:32] WARNING: /workspace/src/learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [13:27:32] WARNING: /workspace/src/learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [13:27:32] WARNING: /workspace/src/learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [13:27:32] WARNING: /workspace/src/learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [13:27:32] WARNING: /w

RFECV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
      estimator=XGBClassifier(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stopping_rounds=None,
                              enable_categorical=False, eval_metric='logloss',
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...),
      scoring='accuracy')

In [20]:
optimal_features = X[:, rfecv.support_]
print("Optimal number of features are: ", rfecv.n_features_)
print("selected features are: ", optimal_features)

Optimal number of features are:  24
selected features are:  [[1.799e+01 1.038e+01 1.001e+03 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.326e+03 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.203e+03 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 8.581e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.265e+03 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 1.810e+02 ... 0.000e+00 2.871e-01 7.039e-02]]
